
package ru.bocharova.tm.endpoint;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-24T15:29:41.834+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "AuthenticationSecurityException", targetNamespace = "http://endpoint.api.tm.bocharova.ru/")
public class AuthenticationSecurityException_Exception extends Exception {

    private AuthenticationSecurityException authenticationSecurityException;

    public AuthenticationSecurityException_Exception() {
        super();
    }

    public AuthenticationSecurityException_Exception(String message) {
        super(message);
    }

    public AuthenticationSecurityException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthenticationSecurityException_Exception(String message,AuthenticationSecurityException authenticationSecurityException) {
        super(message);
        this.authenticationSecurityException = authenticationSecurityException;
    }

    public AuthenticationSecurityException_Exception(String message, AuthenticationSecurityException authenticationSecurityException, Throwable cause) {
        super(message, cause);
        this.authenticationSecurityException = authenticationSecurityException;
    }

    public AuthenticationSecurityException getFaultInfo() {
        return this.authenticationSecurityException;
    }
}
