
package ru.bocharova.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-24T15:29:41.849+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "DataValidateException", targetNamespace = "http://endpoint.api.tm.bocharova.ru/")
public class DataValidateException_Exception extends Exception {

    private DataValidateException dataValidateException;

    public DataValidateException_Exception() {
        super();
    }

    public DataValidateException_Exception(String message) {
        super(message);
    }

    public DataValidateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataValidateException_Exception(String message, DataValidateException dataValidateException) {
        super(message);
        this.dataValidateException = dataValidateException;
    }

    public DataValidateException_Exception(String message, DataValidateException dataValidateException, Throwable cause) {
        super(message, cause);
        this.dataValidateException = dataValidateException;
    }

    public DataValidateException getFaultInfo() {
        return this.dataValidateException;
    }
}
