
package ru.bocharova.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-24T15:29:41.258+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.bocharova.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/editProjectRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/editProjectResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/editProject/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/editProject/Fault/DataValidateException")})
    @RequestWrapper(localName = "editProject", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditProject")
    @ResponseWrapper(localName = "editProjectResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditProjectResponse")
    public void editProject(
            @WebParam(name = "session", targetNamespace = "")
                   SessionDTO session,
            @WebParam(name = "project", targetNamespace = "")
                    ProjectDTO project
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeAllProjectByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeAllProjectByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeAllProjectByUserId/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeAllProjectByUserId/Fault/DataValidateException")})
    @RequestWrapper(localName = "removeAllProjectByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllProjectByUserId")
    @ResponseWrapper(localName = "removeAllProjectByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllProjectByUserIdResponse")
    public void removeAllProjectByUserId(
            @WebParam(name = "session", targetNamespace = "")
                    SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeProjectRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeProjectResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeProject/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/removeProject/Fault/DataValidateException")})
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveProjectResponse")
    public void removeProject(
            @WebParam(name = "session", targetNamespace = "")
                 SessionDTO session,
            @WebParam(name = "id", targetNamespace = "")
                    String id
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findOneProjectRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findOneProjectResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findOneProject/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findOneProject/Fault/DataValidateException")})
    @RequestWrapper(localName = "findOneProject", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindOneProject")
    @ResponseWrapper(localName = "findOneProjectResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindOneProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ProjectDTO findOneProject(
            @WebParam(name = "session", targetNamespace = "")
                  SessionDTO session,
            @WebParam(name = "id", targetNamespace = "")
                    String id
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/createProjectRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/createProjectResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/createProject/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/createProject/Fault/DataValidateException")})
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateProjectResponse")
    public void createProject(
            @WebParam(name = "session", targetNamespace = "")
                   SessionDTO session,
            @WebParam(name = "project", targetNamespace = "")
                 ProjectDTO project
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByUserId/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByUserId/Fault/DataValidateException")})
    @RequestWrapper(localName = "findAllProjectByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllProjectByUserId")
    @ResponseWrapper(localName = "findAllProjectByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllProjectByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ProjectDTO> findAllProjectByUserId(
            @WebParam(name = "session", targetNamespace = "")
                  SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/sortAllProjectByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/sortAllProjectByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/sortAllProjectByUserId/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/sortAllProjectByUserId/Fault/DataValidateException")})
    @RequestWrapper(localName = "sortAllProjectByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.SortAllProjectByUserId")
    @ResponseWrapper(localName = "sortAllProjectByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.SortAllProjectByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ProjectDTO> sortAllProjectByUserId(
            @WebParam(name = "session", targetNamespace = "")
                    SessionDTO session,
            @WebParam(name = "parameter", targetNamespace = "")
                    String parameter
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByPartOfNameOrDescriptionRequest", output = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByPartOfNameOrDescriptionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByPartOfNameOrDescription/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ProjectEndpoint/findAllProjectByPartOfNameOrDescription/Fault/DataValidateException")})
    @RequestWrapper(localName = "findAllProjectByPartOfNameOrDescription", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllProjectByPartOfNameOrDescription")
    @ResponseWrapper(localName = "findAllProjectByPartOfNameOrDescriptionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllProjectByPartOfNameOrDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ProjectDTO> findAllProjectByPartOfNameOrDescription(
            @WebParam(name = "session", targetNamespace = "")
                    SessionDTO session,
            @WebParam(name = "name", targetNamespace = "")
                    String name,
            @WebParam(name = "description", targetNamespace = "")
                    String description
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;
}
