
package ru.bocharova.tm.api.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-23T22:22:32.111+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "AuthenticationSecurityException", targetNamespace = "http://endpoint.api.tm.bocharova.ru/")
public class AuthenticationSecurityException_Exception extends Exception {

    private ru.bocharova.tm.api.endpoint.AuthenticationSecurityException authenticationSecurityException;

    public AuthenticationSecurityException_Exception() {
        super();
    }

    public AuthenticationSecurityException_Exception(String message) {
        super(message);
    }

    public AuthenticationSecurityException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AuthenticationSecurityException_Exception(String message, ru.bocharova.tm.api.endpoint.AuthenticationSecurityException authenticationSecurityException) {
        super(message);
        this.authenticationSecurityException = authenticationSecurityException;
    }

    public AuthenticationSecurityException_Exception(String message, ru.bocharova.tm.api.endpoint.AuthenticationSecurityException authenticationSecurityException, java.lang.Throwable cause) {
        super(message, cause);
        this.authenticationSecurityException = authenticationSecurityException;
    }

    public ru.bocharova.tm.api.endpoint.AuthenticationSecurityException getFaultInfo() {
        return this.authenticationSecurityException;
    }
}
