package ru.bocharova.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-11T16:26:48.582+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.bocharova.ru/", name = "ISessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSessionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSession/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CloseSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Session closeSession(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateSessionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateSession/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "validateSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ValidateSession")
    @ResponseWrapper(localName = "validateSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ValidateSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean validateSession(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSessionResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSession/Fault/IOException"), @FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSession/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "openSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.OpenSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Session openSession(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws IOException_Exception, AuthenticationSecurityException_Exception;
}
