package ru.bocharova.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-23T22:22:31.814+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.bocharova.ru/", name = "ISessionEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ISessionEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSessionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSession/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/closeSession/Fault/DataValidateException")})
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CloseSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.SessionDTO closeSession(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSessionResponse", fault = {@FaultAction(className = IOException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSession/Fault/IOException"), @FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSession/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/openSession/Fault/DataValidateException")})
    @RequestWrapper(localName = "openSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.OpenSessionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.SessionDTO openSession(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws IOException_Exception, AuthenticationSecurityException_Exception, DataValidateException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateAdminSessionRequest", output = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateAdminSessionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateAdminSession/Fault/AuthenticationSecurityException"), @FaultAction(className = DataValidateException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ISessionEndpoint/validateAdminSession/Fault/DataValidateException")})
    @RequestWrapper(localName = "validateAdminSession", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ValidateAdminSession")
    @ResponseWrapper(localName = "validateAdminSessionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.ValidateAdminSessionResponse")
    public void validateAdminSession(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.SessionDTO session
    ) throws AuthenticationSecurityException_Exception, DataValidateException_Exception;
}
