package ru.bocharova.tm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-07-11T16:26:48.723+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.tm.bocharova.ru/", name = "ITaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/editTaskRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/editTaskResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/editTask/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "editTask", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditTask")
    @ResponseWrapper(localName = "editTaskResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.EditTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Task editTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByUserId/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "findAllTaskByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByUserId")
    @ResponseWrapper(localName = "findAllTaskByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.bocharova.tm.api.endpoint.Task> findAllTaskByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeTaskRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeTaskResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeTask/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Task removeTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findOneTaskRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findOneTaskResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findOneTask/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "findOneTask", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindOneTask")
    @ResponseWrapper(localName = "findOneTaskResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindOneTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Task findOneTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByProjectIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByProjectIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByProjectId/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "findAllTaskByProjectId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByProjectId")
    @ResponseWrapper(localName = "findAllTaskByProjectIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.bocharova.tm.api.endpoint.Task> findAllTaskByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/sortAllTaskByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/sortAllTaskByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/sortAllTaskByUserId/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "sortAllTaskByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.SortAllTaskByUserId")
    @ResponseWrapper(localName = "sortAllTaskByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.SortAllTaskByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.bocharova.tm.api.endpoint.Task> sortAllTaskByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "comparator", targetNamespace = "")
        java.lang.String comparator
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByProjectIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByProjectIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByProjectId/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "removeAllTaskByProjectId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllTaskByProjectId")
    @ResponseWrapper(localName = "removeAllTaskByProjectIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllTaskByProjectIdResponse")
    public void removeAllTaskByProjectId(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByPartOfNameOrDescriptionRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByPartOfNameOrDescriptionResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/findAllTaskByPartOfNameOrDescription/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "findAllTaskByPartOfNameOrDescription", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByPartOfNameOrDescription")
    @ResponseWrapper(localName = "findAllTaskByPartOfNameOrDescriptionResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.FindAllTaskByPartOfNameOrDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.bocharova.tm.api.endpoint.Task> findAllTaskByPartOfNameOrDescription(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByUserIdRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByUserIdResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/removeAllTaskByUserId/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "removeAllTaskByUserId", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllTaskByUserId")
    @ResponseWrapper(localName = "removeAllTaskByUserIdResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.RemoveAllTaskByUserIdResponse")
    public void removeAllTaskByUserId(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session
    ) throws AuthenticationSecurityException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/createTaskRequest", output = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/createTaskResponse", fault = {@FaultAction(className = AuthenticationSecurityException_Exception.class, value = "http://endpoint.api.tm.bocharova.ru/ITaskEndpoint/createTask/Fault/AuthenticationSecurityException")})
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.api.tm.bocharova.ru/", className = "ru.bocharova.tm.api.endpoint.CreateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.bocharova.tm.api.endpoint.Task createTask(
        @WebParam(name = "session", targetNamespace = "")
        ru.bocharova.tm.api.endpoint.Session session,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    ) throws AuthenticationSecurityException_Exception;
}
